# Generated by Django 4.0.6 on 2022-07-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prefix', models.CharField(choices=[('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Ms', 'Ms'), ('Dr', 'Dr')], max_length=4)),
                ('First_name', models.CharField(blank=True, default='', max_length=50)),
                ('Last_name', models.CharField(blank=True, default='', max_length=50)),
                ('Email', models.CharField(blank=True, default='', max_length=60)),
                ('Username', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
    ]
