# Generated by Django 4.0.6 on 2022-07-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Dr', 'Dr'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Ms', 'Ms')], max_length=4),
        ),
    ]
