# Generated by Django 4.0.6 on 2022-07-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Ms', 'Ms'), ('Dr', 'Dr'), ('Mrs', 'Mrs'), ('Mr', 'Mr')], max_length=4),
        ),
    ]
