# Generated by Django 4.0.6 on 2022-07-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Dr', 'Dr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Mr', 'Mr')], max_length=4),
        ),
    ]
